name: Run Pre Publish Checks
on: [push]
jobs:
  Explore-GitHub-Stacks:
    runs-on: ubuntu-latest
    steps:
      - id: prepublish
        uses: sundargs2000/stacks-pre-publish@master

      # Uncomment the step below if you want a release to be created on every commit
      
      # - name: Create Release
      #   if: ${{ steps.prepublish.outputs.success == 'true' }}
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      #   with:
      #     tag_name: v1.${{ github.sha }}
      #     release_name: Release stack/${{ github.ref }}
