name: Create the files.

on:
  workflow_dispatch:

jobs:
  stack-initialization:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
      
      - name: move the file
        run: |
          mkdir .github/stacks
          mv ./instance-contents/new-stack.yml .github/stacks/stack.yml
          mv ./instance-contents/README.md ./README.md
          rm -r ./instance-contents
      
      - name: Commit files
        run: |
          git config --global user.name '${{github.actor}}'
          git config --global user.email '${{github.actor}}@users.noreply.github.com'
          git add -A
          git commit -m "Added readme and stack template."
          git push
